# Homebrew formula TEMPLATE for casual.
#
# To use it after you cut a GitHub release (git tag v0.4.0 && git push --tags):
#   1. Set `url` to the release tarball.
#   2. Fill `sha256` with:  curl -sL <url> | shasum -a 256
#   3. Put this file in a tap (e.g. LAOUUUUU/homebrew-tap) and:
#        brew install LAOUUUUU/tap/casual
#
# Adjust `homepage`/`url` to your actual repo (owner shown is a placeholder).
class Casual < Formula
  desc "Modular CLI toolkit: network diagnostics, logging proxy, file scanner, plugins"
  homepage "https://github.com/LAOUUUUU/casual"
  url "https://github.com/LAOUUUUU/casual/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "REPLACE_WITH_SHA256"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
    # Install shell completions generated by the binary itself.
    generate_completions_from_executable(bin/"casual", "completions")
  end

  test do
    assert_match "casual", shell_output("#{bin}/casual --version")
  end
end
