//! `casual learn` — watch a model actually learn, live in the terminal.
//!
//! Trains a classifier on a toy 2-D dataset and redraws the decision boundary
//! every few epochs so you can see it form while the loss falls. No ML crates,
//! no randomness crate — data is generated by a tiny reproducible LCG.
//!
//! Two teaching knobs:
//!   --dataset blobs   two separable blobs (a single neuron nails it)
//!   --dataset xor     the classic XOR — a single neuron CANNOT solve it, but
//!                     add `--hidden 4` and a hidden layer suddenly can. Seeing
//!                     that failure then fix is the whole point.
//!   --csv points.csv  bring your own data (rows of: x,y,label   label 0 or 1)

use anyhow::{Context, Result};
use clap::Args;
use std::io::Write;
use std::path::PathBuf;
use std::thread;
use std::time::Duration;

#[derive(Args)]
pub struct LearnArgs {
    /// Which toy dataset: "blobs" or "xor" (ignored if --csv is given).
    #[arg(short, long, default_value = "blobs")]
    pub dataset: String,

    /// Hidden units. 0 = a single neuron (logistic regression); >0 = an MLP.
    #[arg(long, default_value_t = 0)]
    pub hidden: usize,

    /// Load points from a CSV instead (rows: x,y,label).
    #[arg(long)]
    pub csv: Option<PathBuf>,

    /// Training epochs.
    #[arg(short, long, default_value_t = 120)]
    pub epochs: usize,

    /// Learning rate.
    #[arg(short, long, default_value_t = 0.2)]
    pub lr: f64,

    /// Redraw the board every N epochs.
    #[arg(long, default_value_t = 4)]
    pub every: usize,

    /// Skip the animation delay (dump frames as fast as possible).
    #[arg(long)]
    pub fast: bool,
}

const GRID_W: usize = 51;
const GRID_H: usize = 21;
const RANGE: f64 = 4.0;

struct Point {
    x: f64,
    y: f64,
    label: f64,
}

/// A reproducible linear-congruential generator.
struct Lcg(u64);
impl Lcg {
    fn unit(&mut self) -> f64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        ((self.0 >> 11) as f64) / ((1u64 << 53) as f64)
    }
    fn gaussian(&mut self) -> f64 {
        (self.unit() + self.unit() + self.unit() + self.unit()) - 2.0
    }
    fn small(&mut self) -> f64 {
        self.unit() - 0.5
    }
}

/// The model. `Linear` is one neuron; `Mlp` is one tanh hidden layer.
enum Model {
    Linear {
        w: [f64; 2],
        b: f64,
    },
    Mlp {
        w1: Vec<[f64; 2]>,
        b1: Vec<f64>,
        w2: Vec<f64>,
        b2: f64,
    },
}

impl Model {
    fn new(hidden: usize, rng: &mut Lcg) -> Model {
        if hidden == 0 {
            Model::Linear {
                w: [0.0, 0.0],
                b: 0.0,
            }
        } else {
            Model::Mlp {
                w1: (0..hidden).map(|_| [rng.small(), rng.small()]).collect(),
                b1: (0..hidden).map(|_| rng.small()).collect(),
                w2: (0..hidden).map(|_| rng.small()).collect(),
                b2: rng.small(),
            }
        }
    }

    fn predict(&self, x: f64, y: f64) -> f64 {
        match self {
            Model::Linear { w, b } => sigmoid(w[0] * x + w[1] * y + b),
            Model::Mlp { w1, b1, w2, b2 } => {
                let mut z = *b2;
                for j in 0..w1.len() {
                    let h = (w1[j][0] * x + w1[j][1] * y + b1[j]).tanh();
                    z += w2[j] * h;
                }
                sigmoid(z)
            }
        }
    }

    fn loss(&self, data: &[Point]) -> f64 {
        let sum: f64 = data
            .iter()
            .map(|p| bce(self.predict(p.x, p.y), p.label))
            .sum();
        sum / data.len() as f64
    }

    fn update(&mut self, data: &[Point], lr: f64) {
        let n = data.len() as f64;
        match self {
            Model::Linear { w, b } => {
                let (mut g0, mut g1, mut gb) = (0.0, 0.0, 0.0);
                for p in data {
                    let dz = sigmoid(w[0] * p.x + w[1] * p.y + *b) - p.label;
                    g0 += dz * p.x;
                    g1 += dz * p.y;
                    gb += dz;
                }
                w[0] -= lr * g0 / n;
                w[1] -= lr * g1 / n;
                *b -= lr * gb / n;
            }
            Model::Mlp { w1, b1, w2, b2 } => {
                let hidden = w1.len();
                let mut gw1 = vec![[0.0f64; 2]; hidden];
                let mut gb1 = vec![0.0f64; hidden];
                let mut gw2 = vec![0.0f64; hidden];
                let mut gb2 = 0.0f64;

                for p in data {
                    // Forward, remembering hidden activations.
                    let mut h = vec![0.0f64; hidden];
                    let mut z = *b2;
                    for j in 0..hidden {
                        h[j] = (w1[j][0] * p.x + w1[j][1] * p.y + b1[j]).tanh();
                        z += w2[j] * h[j];
                    }
                    let dz = sigmoid(z) - p.label; // dL/dz (sigmoid + BCE)
                    // Backprop.
                    for j in 0..hidden {
                        gw2[j] += dz * h[j];
                        let da = dz * w2[j] * (1.0 - h[j] * h[j]); // tanh'
                        gw1[j][0] += da * p.x;
                        gw1[j][1] += da * p.y;
                        gb1[j] += da;
                    }
                    gb2 += dz;
                }
                for j in 0..hidden {
                    w1[j][0] -= lr * gw1[j][0] / n;
                    w1[j][1] -= lr * gw1[j][1] / n;
                    b1[j] -= lr * gb1[j] / n;
                    w2[j] -= lr * gw2[j] / n;
                }
                *b2 -= lr * gb2 / n;
            }
        }
    }
}

pub fn run(args: LearnArgs) -> Result<()> {
    let mut rng = Lcg(0x9E3779B97F4A7C15);
    let data = match &args.csv {
        Some(path) => load_csv(path)?,
        None => make_dataset(&args.dataset, &mut rng)?,
    };
    if data.is_empty() {
        anyhow::bail!("no data points to train on");
    }

    let mut model = Model::new(args.hidden, &mut rng);
    let mut losses: Vec<f64> = Vec::new();

    for epoch in 0..=args.epochs {
        let loss = model.loss(&data);
        losses.push(loss);

        if epoch % args.every == 0 || epoch == args.epochs {
            draw(epoch, args.epochs, loss, &model, &data, &losses, &args);
            if !args.fast {
                thread::sleep(Duration::from_millis(60));
            }
        }
        if epoch != args.epochs {
            model.update(&data, args.lr);
        }
    }

    let acc = accuracy(&data, &model);
    println!(
        "\nfinal: loss {:.4}, accuracy {:.0}%   ({} pts, {} hidden units)",
        losses.last().copied().unwrap_or(0.0),
        acc * 100.0,
        data.len(),
        args.hidden
    );
    if args.hidden == 0 && args.dataset == "xor" && args.csv.is_none() {
        println!(
            "note: a single neuron tops out around 50% on XOR. Try: casual learn --dataset xor --hidden 4"
        );
    }
    println!("(o = class A, x = class B, shaded = model predicts class B)");
    Ok(())
}

fn make_dataset(kind: &str, rng: &mut Lcg) -> Result<Vec<Point>> {
    let mut pts = Vec::new();
    match kind {
        "blobs" => {
            for _ in 0..60 {
                pts.push(Point {
                    x: rng.gaussian() - 1.5,
                    y: rng.gaussian() - 1.2,
                    label: 0.0,
                });
                pts.push(Point {
                    x: rng.gaussian() + 1.5,
                    y: rng.gaussian() + 1.2,
                    label: 1.0,
                });
            }
        }
        "xor" => {
            // class 1 where x and y share a sign; class 0 otherwise.
            let centers = [
                (1.5, 1.5, 1.0),
                (-1.5, -1.5, 1.0),
                (1.5, -1.5, 0.0),
                (-1.5, 1.5, 0.0),
            ];
            for _ in 0..30 {
                for &(cx, cy, label) in &centers {
                    pts.push(Point {
                        x: cx + rng.gaussian() * 0.6,
                        y: cy + rng.gaussian() * 0.6,
                        label,
                    });
                }
            }
        }
        other => anyhow::bail!("unknown dataset '{other}' (use blobs or xor, or pass --csv)"),
    }
    Ok(pts)
}

fn load_csv(path: &PathBuf) -> Result<Vec<Point>> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let mut pts = Vec::new();
    for (i, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let cols: Vec<&str> = line.split(',').map(|s| s.trim()).collect();
        if cols.len() < 3 {
            continue;
        }
        // Skip a header row (first line that doesn't parse as numbers).
        let (Ok(x), Ok(y), Ok(label)) = (
            cols[0].parse::<f64>(),
            cols[1].parse::<f64>(),
            cols[2].parse::<f64>(),
        ) else {
            if i == 0 {
                continue;
            }
            anyhow::bail!("bad numeric row in {}: {line}", path.display());
        };
        pts.push(Point {
            x,
            y,
            label: if label >= 0.5 { 1.0 } else { 0.0 },
        });
    }
    Ok(pts)
}

#[allow(clippy::too_many_arguments)]
fn draw(
    epoch: usize,
    total: usize,
    loss: f64,
    model: &Model,
    data: &[Point],
    losses: &[f64],
    args: &LearnArgs,
) {
    print!("\x1b[2J\x1b[H");

    let mut grid = vec![vec![' '; GRID_W]; GRID_H];
    for (row, line) in grid.iter_mut().enumerate() {
        for (col, cell) in line.iter_mut().enumerate() {
            let (x, y) = cell_to_xy(col, row);
            *cell = if model.predict(x, y) >= 0.5 {
                '·'
            } else {
                ' '
            };
        }
    }
    for p in data {
        if let Some((col, row)) = xy_to_cell(p.x, p.y) {
            grid[row][col] = if p.label < 0.5 { 'o' } else { 'x' };
        }
    }

    let kind = if args.csv.is_some() {
        "csv"
    } else {
        &args.dataset
    };
    println!(
        "casual learn [{kind}, hidden={}] — epoch {epoch}/{total}   loss {loss:.4}",
        args.hidden
    );
    println!("+{}+", "-".repeat(GRID_W));
    for line in &grid {
        let s: String = line.iter().collect();
        println!("|{s}|");
    }
    println!("+{}+", "-".repeat(GRID_W));
    println!("loss  {}", sparkline(losses));
    let _ = std::io::stdout().flush();
}

fn cell_to_xy(col: usize, row: usize) -> (f64, f64) {
    let x = -RANGE + (col as f64 / (GRID_W - 1) as f64) * (2.0 * RANGE);
    let y = RANGE - (row as f64 / (GRID_H - 1) as f64) * (2.0 * RANGE);
    (x, y)
}

fn xy_to_cell(x: f64, y: f64) -> Option<(usize, usize)> {
    if x < -RANGE || x > RANGE || y < -RANGE || y > RANGE {
        return None;
    }
    let col = ((x + RANGE) / (2.0 * RANGE) * (GRID_W - 1) as f64).round() as usize;
    let row = ((RANGE - y) / (2.0 * RANGE) * (GRID_H - 1) as f64).round() as usize;
    Some((col.min(GRID_W - 1), row.min(GRID_H - 1)))
}

fn sparkline(values: &[f64]) -> String {
    if values.is_empty() {
        return String::new();
    }
    let bars = ['▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'];
    let (mut lo, mut hi) = (f64::INFINITY, f64::NEG_INFINITY);
    for &v in values {
        lo = lo.min(v);
        hi = hi.max(v);
    }
    let span = (hi - lo).max(1e-9);
    values
        .iter()
        .map(|&v| {
            let idx = (((v - lo) / span) * (bars.len() - 1) as f64).round() as usize;
            bars[idx.min(bars.len() - 1)]
        })
        .collect()
}

fn accuracy(data: &[Point], model: &Model) -> f64 {
    let correct = data
        .iter()
        .filter(|p| (model.predict(p.x, p.y) >= 0.5) == (p.label >= 0.5))
        .count();
    correct as f64 / data.len() as f64
}

fn sigmoid(z: f64) -> f64 {
    1.0 / (1.0 + (-z).exp())
}

fn bce(pred: f64, label: f64) -> f64 {
    let eps = 1e-12;
    let p = pred.clamp(eps, 1.0 - eps);
    -(label * p.ln() + (1.0 - label) * (1.0 - p).ln())
}
